apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: tellmeall
  namespace: demo
spec:
  runLatest:
    configuration:
      revisionTemplate:
        metadata:
          labels:
            demo: tellmeall
        spec:
          container:
            image: gcr.io/knative-samples/tellmeall:latest
            imagePullPolicy: Always
            resources:
              requests:
                memory: "128Mi"
                cpu: "0.5"
                nvidia.com/gpu: 1
              limits:
                memory: "1Gi"
                cpu: "1"
            env:
            - name: RELEASE
              value: "v0.5.30"
            - name: LOG_TO_FILE
              value: "yes"