apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: tellmeall
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: gcr.io/knative-samples/tellmeall:latest
            imagePullPolicy: Always
            env:
            - name: RELEASE
              value: "v0.4.1"
            - name: LOG_TO_FILE
              value: "yes"